### ISSUE TITLE
The Checklist

### ISSUE THREAD

**Issue by madjin** [gm3/boomboxheads-v2-assets#14]
- [x] Optimization
  - [x] LOD?
    - [x] test gltf-transform optimize: https://gltf-transform.donmccurdy.com/cli.html
    - [x] test gltf-transform LOD script: https://github.com/takahirox/glTF-Transform-lod-script
    
```bash
node generate_lod.mjs in.glb out.glb \
 --ratio 0.5,0.1 \
 --error 0.01,0.05 \
 --coverage 0.7,0.3,0.0 \
 --texture 512x512,128x128
```

- [x] #25
  - [x] Try embedding into glTF via: https://github.com/matrix-org/thirdroom-unity-exporter
- [x] Upload data to IPFS
  - [x] web3.storage
  - [x] [estuary.tech](https://estuary.tech/) (Zora / Internet Archive use it, pins to 6 places)
- [x] Get allow list ready
- [x] Upload unity recording video to #media channel / somewhere to share

https://user-images.githubusercontent.com/32600939/224568010-2582e86a-6ac5-46dd-bcf0-bddbe1582d11.mp4
